"""
Full RLHF Training Loop with PPO
=================================
Implements the final stage of the classical RLHF pipeline (Stiennon et al.,
2020; Ouyang et al., 2022): the policy (initialised from the SFT model)
generates responses to prompts, the frozen reward model scores them, and PPO
updates the policy to maximise reward minus a per-token KL penalty against the
frozen reference policy pi_ref. Uses trl.experimental.ppo.PPOTrainer (the PPO
implementation moved to trl.experimental in TRL v1), which runs generation,
scoring, and the PPO update internally from a single train() call.

Inputs
------
config : PPORunConfig — SFT and reward-model paths (adapter directories are
         merged automatically), LoRA settings for the policy, episode budget,
         batch sizes, generation settings, and the KL coefficient beta.

Outputs
-------
PPO policy LoRA adapter saved to ./results/ppo_rlhf_loop/adapter_<label>/;
objective/kl, objective/scores, objective/rlhf_reward, and loss curves logged
to TensorBoard; sample completions logged during training.

Dataset
-------
Anthropic/hh-rlhf — prompts are extracted from the 'chosen' dialogues (text up
to and including the final '\\n\\nAssistant:' turn marker); responses are
generated by the policy, not taken from the dataset.

Public API
----------
train(config)               — run the PPO loop; return the fitted PPOTrainer.
extract_prompt(text)        — strip the final assistant response from an HH-RLHF dialogue.
"""

# stdlib
import hashlib
import json
import os
import sys
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone

# Reduce CUDA allocator fragmentation on long, variable-length runs. Must be set
# before torch initialises the CUDA context; harmless on non-CUDA backends.
os.environ.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")

# Using trl.experimental.ppo is a deliberate, documented choice (PPO moved to
# trl.experimental in TRL v1; see README and reports), and the TRL version is
# pinned by uv.lock, so the import-time TRLExperimentalWarning adds no
# information. This is TRL's sanctioned silencing mechanism; setdefault means
# TRL_EXPERIMENTAL_SILENCE=0 in the shell re-enables the warning.
os.environ.setdefault("TRL_EXPERIMENTAL_SILENCE", "1")

# third-party
import torch
from datasets import Dataset, load_dataset
from peft import LoraConfig
from rich.console import Console
from transformers import (
    AutoModelForCausalLM,
    AutoModelForSequenceClassification,
    AutoTokenizer,
    HfArgumentParser,
    PreTrainedTokenizer,
)
from trl.experimental.ppo import PPOConfig, PPOTrainer

# local
from ..common.config import PROJECT_ROOT, SFT_ADAPTER, RM_MODEL, PPO_ADAPTER
from ..common.model_utils import resolve_model_path, CacheCleaner, export_canonical

RESULT_PATH = f"{PROJECT_ROOT}/results/ppo_rlhf_loop"

console = Console()


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

@dataclass
class PPORunConfig:
    # None → the artefacts produced by the previous stages with default settings.
    sft_model_path: str | None = None
    rm_model_path:  str | None = None
    dataset_name:   str = "Anthropic/hh-rlhf"
    seed:           int = 42

    # LoRA on the policy. With a PEFT policy, no separate reference model is
    # needed: disabling the adapters recovers pi_ref exactly.
    lora_r:       int   = 32
    lora_alpha:   int   = 64
    lora_dropout: float = 0.05
    lora_target_modules: list[str] = field(default_factory=lambda: ["q_proj", "v_proj"])

    # PPO optimisation
    learning_rate:               float = 1e-5
    total_episodes:              int   = 10_000
    per_device_train_batch_size: int   = 4
    gradient_accumulation_steps: int   = 4
    num_ppo_epochs:              int   = 4     # optimisation passes per rollout batch
    num_mini_batches:            int   = 1
    kl_coef:                     float = 0.2   # beta; fixed (no adaptive controller in TRL v1)
    gradient_checkpointing:      bool  = True  # trades recompute for activation memory

    # Generation
    response_length:     int   = 128   # generation budget (max new tokens), not a sequence cap
    temperature:         float = 0.7
    missing_eos_penalty: float = 1.0   # reward penalty when a response never emits EOS
    max_prompt_tokens:   int   = 256   # longer prompts are filtered out (not truncated)
    rollout_batch_size:  int   = 4     # forward batch size during rollouts

    # Evaluation and logging
    eval_examples: int = 100
    report_to:     str = "tensorboard"
    # TRL's PPO loop prints its own metrics every update regardless of this
    # value; it gates other consumers of args.logging_steps, e.g. CacheCleaner's
    # [mem] line. Without it, the TrainingArguments default (500) applies.
    logging_steps: int = 10
    # The experimental PPOTrainer cannot resume (train() takes no arguments),
    # so checkpoints exist only for manual adapter recovery after a crash. The
    # TrainingArguments default (500) would give a ~625-update run a single
    # mid-run checkpoint; 100 keeps the worst-case loss to ~100 updates.
    save_steps: int = 100

    def __post_init__(self) -> None:
        if self.sft_model_path is None:
            self.sft_model_path = SFT_ADAPTER
        if self.rm_model_path is None:
            self.rm_model_path = RM_MODEL
        if self.max_prompt_tokens <= 0:
            raise ValueError(f"max_prompt_tokens ({self.max_prompt_tokens}) must be positive.")

    @property
    def label(self) -> str:
        # Hash the FULL config so any hyperparameter change yields a distinct
        # label and its own results directory, preventing different experiments
        # from silently overwriting each other's artefacts.
        config_str = json.dumps(asdict(self), sort_keys=True)
        return hashlib.md5(config_str.encode()).hexdigest()[:8]


# ---------------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------------

def train(config: PPORunConfig) -> PPOTrainer:
    """Run the full PPO RLHF loop and save the policy adapter.

    Reads as the algorithm outline: resolve the SFT and reward-model
    artefacts into loadable models, prepare tokenised prompts, assemble the
    four-model PPO trainer (with the reference obtained by adapter
    disabling), train, and persist.

    Args:
        config: Hyperparameter configuration.

    Returns:
        The fitted PPOTrainer (gives access to the trained policy).
    """
    sft_path = resolve_model_path(config.sft_model_path, "causal-lm")
    rm_path  = resolve_model_path(config.rm_model_path, "seq-cls")

    tokenizer                          = _load_tokenizer(sft_path)
    policy, reward_model, value_model  = _load_models(sft_path, rm_path, tokenizer)
    train_ds, eval_ds                  = _build_prompt_datasets(config, tokenizer)
    trainer                            = _build_trainer(
        policy, reward_model, value_model, tokenizer, train_ds, eval_ds, config
    )

    trainer.train()

    adapter_path = f"{RESULT_PATH}/adapter_{config.label}"
    trainer.save_model(adapter_path)
    console.print(f"[green]PPO policy adapter saved to[/green] {adapter_path}")

    return trainer


def _load_tokenizer(model_path: str) -> PreTrainedTokenizer:
    """Load the tokenizer with left padding for batched generation.

    Decoder-only models generate from the rightmost position, so prompt
    batches must be left-padded; right padding would make the model continue
    from pad tokens.
    """
    tokenizer = AutoTokenizer.from_pretrained(model_path, padding_side="left")
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    return tokenizer


def _load_models(
    sft_path: str, rm_path: str, tokenizer: PreTrainedTokenizer
) -> tuple[torch.nn.Module, torch.nn.Module, torch.nn.Module]:
    """Load the policy, frozen reward model, and critic.

    Three models rather than four: the frozen reference is not loaded, because
    the policy is trained with LoRA and PPOTrainer recovers pi_ref by
    disabling the adapters (the base weights are exactly the SFT model).
    The critic is initialised from the reward model, which already maps
    response prefixes to scalar quality estimates — a far better starting
    point for value prediction than a fresh head.
    """
    policy = AutoModelForCausalLM.from_pretrained(sft_path, dtype=torch.bfloat16)

    reward_model = AutoModelForSequenceClassification.from_pretrained(
        rm_path, num_labels=1, dtype=torch.bfloat16
    )
    value_model = AutoModelForSequenceClassification.from_pretrained(
        rm_path, num_labels=1, dtype=torch.bfloat16
    )
    for model in (policy, reward_model, value_model):
        model.config.pad_token_id = tokenizer.pad_token_id

    return policy, reward_model, value_model


def extract_prompt(text: str) -> str:
    """Strip the final assistant response from an HH-RLHF dialogue.

    HH-RLHF stores whole dialogues; PPO needs only the prompt and generates
    the response itself. Everything up to and including the last
    '\\n\\nAssistant:' marker is the prompt.
    """
    marker = "\n\nAssistant:"
    return text[: text.rindex(marker) + len(marker)]


def _build_prompt_datasets(
    config: PPORunConfig, tokenizer: PreTrainedTokenizer
) -> tuple[Dataset, Dataset]:
    """Extract, tokenise, and length-filter prompts; split off an eval set.

    PPOTrainer expects pre-tokenised prompts in an 'input_ids' column. Long
    prompts are filtered out (not truncated): a truncated dialogue can lose
    the actual question, leaving the policy to optimise reward on nonsense.
    """
    dataset = load_dataset(config.dataset_name, split="train")
    dataset = dataset.map(
        lambda example: tokenizer(extract_prompt(example["chosen"])),
        remove_columns=dataset.column_names,
    )
    dataset = dataset.filter(
        lambda example: len(example["input_ids"]) <= config.max_prompt_tokens
    )
    split = dataset.train_test_split(test_size=config.eval_examples, seed=config.seed)
    return split["train"], split["test"]


def _build_trainer(
    policy:       torch.nn.Module,
    reward_model: torch.nn.Module,
    value_model:  torch.nn.Module,
    tokenizer:    PreTrainedTokenizer,
    train_ds:     Dataset,
    eval_ds:      Dataset,
    config:       PPORunConfig,
) -> PPOTrainer:
    """Assemble the PPOTrainer with a LoRA policy and no explicit reference."""
    lora_config = LoraConfig(
        r=config.lora_r,
        lora_alpha=config.lora_alpha,
        target_modules=config.lora_target_modules,
        lora_dropout=config.lora_dropout,
        task_type="CAUSAL_LM",
    )
    # logging_dir is deprecated; the TensorBoard integration now reads this env var.
    os.environ["TENSORBOARD_LOGGING_DIR"] = f"{RESULT_PATH}/tb/{config.label}"

    ppo_config = PPOConfig(
        output_dir=f"{RESULT_PATH}/checkpoints_{config.label}",
        learning_rate=config.learning_rate,
        total_episodes=config.total_episodes,
        per_device_train_batch_size=config.per_device_train_batch_size,
        gradient_accumulation_steps=config.gradient_accumulation_steps,
        num_ppo_epochs=config.num_ppo_epochs,
        num_mini_batches=config.num_mini_batches,
        local_rollout_forward_batch_size=config.rollout_batch_size,
        kl_coef=config.kl_coef,
        response_length=config.response_length,
        temperature=config.temperature,
        stop_token="eos",   # truncate responses at EOS before scoring
        missing_eos_penalty=config.missing_eos_penalty,
        gradient_checkpointing=config.gradient_checkpointing,
        gradient_checkpointing_kwargs={"use_reentrant": False},
        bf16=True,
        logging_steps=config.logging_steps,
        save_steps=config.save_steps,
        report_to=config.report_to,
        seed=config.seed,
    )
    return PPOTrainer(
        args=ppo_config,
        processing_class=tokenizer,
        model=policy,
        ref_model=None,             # pi_ref = policy with adapters disabled
        reward_model=reward_model,
        value_model=value_model,
        train_dataset=train_ds,
        eval_dataset=eval_ds,
        peft_config=lora_config,
        callbacks=[CacheCleaner()],
    )


# ---------------------------------------------------------------------------
# Configuration loading and run records
# ---------------------------------------------------------------------------

def parse_config(argv: list[str] | None = None) -> PPORunConfig:
    """Build a PPORunConfig from the command line or a JSON config file.

    A single argument ending in '.json' is read as a config file; otherwise the
    arguments are parsed as CLI overrides. With no arguments, the dataclass
    defaults are used. This keeps experiments config-driven rather than requiring
    source edits.
    """
    argv = sys.argv[1:] if argv is None else argv
    parser = HfArgumentParser(PPORunConfig)
    if len(argv) == 1 and argv[0].endswith(".json"):
        (config,) = parser.parse_json_file(os.path.abspath(argv[0]))
    else:
        (config,) = parser.parse_args_into_dataclasses(argv)
    return config


def save_config(config: PPORunConfig) -> str:
    """Persist the resolved config to JSON for reproducibility. Returns the path."""
    path = f"{RESULT_PATH}/config_{config.label}.json"
    with open(path, "w") as f:
        json.dump(asdict(config), f, indent=2)
    return path


def save_metrics(trainer: PPOTrainer, config: PPORunConfig) -> str:
    """Persist the final PPO objective metrics to JSON, keyed by run label.

    PPO has no single acceptance gate, so the last logged values of the reward,
    KL, and raw reward-model score are recorded as the run summary. A high KL
    alongside a high reward is the classic reward-hacking signature, so both are
    captured. Keys absent from the log history are written as null.
    """
    def _last(key: str):
        for entry in reversed(trainer.state.log_history):
            if key in entry:
                return entry[key]
        return None

    metrics = {
        "label":              config.label,
        "rlhf_reward":        _last("objective/rlhf_reward"),
        "reward_model_score": _last("objective/scores"),
        "kl":                 _last("objective/kl"),
        # Per-token closed-form entropy, not objective/entropy: the latter sums
        # sampled-token surprisal over the response window with post-EOS slots
        # filled by a sentinel log-probability of 1.0, so it tracks response
        # length rather than entropy. See the PPO report, Section 5.1.
        "entropy":            _last("policy/entropy_avg"),
        "kl_coef":            config.kl_coef,
        "total_episodes":     config.total_episodes,
        "global_step":        trainer.state.global_step,
        "sft_model_path":     config.sft_model_path,
        "rm_model_path":      config.rm_model_path,
        "timestamp_utc":      datetime.now(timezone.utc).isoformat(timespec="seconds"),
    }
    path = f"{RESULT_PATH}/metrics_{config.label}.json"
    with open(path, "w") as f:
        json.dump(metrics, f, indent=2)
    return path


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    os.makedirs(RESULT_PATH, exist_ok=True)

    config = parse_config()
    config_path = save_config(config)
    console.print(
        f"PPO run [bold]{config.label}[/bold]: policy from {config.sft_model_path}, "
        f"reward model from {config.rm_model_path}, beta={config.kl_coef}"
    )
    console.print(f"[green]Resolved config saved to[/green] {config_path}")

    trainer = train(config)

    metrics_path = save_metrics(trainer, config)
    console.print(f"[green]Metrics saved to[/green] {metrics_path}")

    # Opt-in canonical export, as in the other stages. Unlike SFT/RM there is
    # no re-run-to-promote route (train() cannot resume), so a completed run
    # is promoted after the fact with: uv run rlhf-promote ppo <label>
    if os.environ.get("EXPORT_CANONICAL") == "1":
        export_canonical(trainer, PPO_ADAPTER)
        # The same provenance record rlhf-promote writes, so consumers (e.g.
        # the Ollama exporter) can recover the run label either way.
        provenance = {
            "stage":         "ppo",
            "label":         config.label,
            "promoted_from": f"{RESULT_PATH}/adapter_{config.label}",
            "timestamp_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        }
        with open(os.path.join(PPO_ADAPTER, "promoted_from.json"), "w") as f:
            json.dump(provenance, f, indent=2)
        console.print(f"[green]PPO policy adapter exported to canonical path[/green] {PPO_ADAPTER}")
    else:
        console.print(
            f"[dim]EXPORT_CANONICAL not set[/dim] -- canonical path {PPO_ADAPTER} left "
            f"untouched (promote later with: uv run rlhf-promote ppo {config.label})"
        )

    # Qualitative probe: generate completions for the eval prompts so reward
    # hacking artefacts (repetition, format gaming) can be spotted by eye.
    trainer.generate_completions()


if __name__ == "__main__":
    main()


# =============================================================================
# How it works
# =============================================================================
# - train: resolve SFT/RM adapters into merged models, build left-padded
#   tokenised prompts, assemble the PPO trainer, train, save the adapter.
# - TRL v1 API: PPOTrainer (trl.experimental.ppo) owns the whole loop —
#   rollout generation, reward scoring, KL-shaped reward, GAE, and the
#   clipped PPO update all happen inside train(); the old manual
#   generate()/step() loop no longer exists.
# - Memory: classical PPO RLHF needs four models; here the policy is a LoRA
#   PEFT model and ref_model=None, so pi_ref is recovered by disabling the
#   adapters — only one copy of the backbone is held for policy+reference.
# - Critic: the value model is initialised from the reward model, which
#   already estimates response quality, rather than from a fresh scalar head.
# - Prompts: extracted from HH-RLHF 'chosen' dialogues by cutting after the
#   last '\n\nAssistant:'; over-long prompts are filtered, not truncated,
#   to avoid optimising reward on questions that were cut away.
# - Reward shaping: stop_token="eos" truncates responses at EOS before
#   scoring, and missing_eos_penalty subtracts 1.0 when no EOS is produced —
#   closing off the 'ramble to the token limit' reward-hacking route.
# - KL: beta is fixed at 0.2 via kl_coef (the adaptive controller was removed
#   in the TRL rewrite); if objective/kl grows unboundedly, raise beta.
# =============================================================================
